[topflite]
TARGET_IP ansible_user=TARGET_USER ansible_password=TARGET_PW ansible_connection=arubaoscx_rest
TARGET_IP ansible_user=TARGET_USER ansible_password=TARGET_PW ansible_connection=arubaoscx_rest
# Replace TARGET_IP, TARGET_USER and TARGET_PW with the ip, username and password of the switch that shall be configured
# Start Playbook with "ansible-playbook ./playbooks/playbook_name.yml -i hosts.yml"