---
-  hosts: topflite

   tasks:
     - name: Layer2 Interface configuration
       arubaoscx_l2_interface:
         interface: "{{ item.interface }}"
         admin_state: "{{ item.admin_state }}"
         description: "{{ item.description }}"
         vlan_mode: "{{ item.vlan_mode }}"
         vlan_id: "{{ item.vlan_id }}"
         vlan_trunk_native_id: "{{ item.vlan_trunk_native_id }}"
         vlan_trunk_native_tag: "{{ item.vlan_trunk_native_tag }}"
         qos_rate: "{{ item.qos_rate }}"
         qos_schedule_profile: "{{ item.qos_schedule_profile }}"
         aclv6_in: "{{ item.aclv6_in }}"
         aclv4_in: "{{ item.aclv4_in }}"
         aclmac_in: "{{ item.aclmac_in }}"
         state: "{{ item.state }}"
       with_items:
         - { interface: 1/1/3, admin_state: up, description: 'This is interface 1/1/2', vlan_mode: trunk, vlan_id: [1,2], vlan_trunk_native_id: 2, vlan_trunk_native_tag: true, qos_rate: {'unknown-unicast': 100pps, 'broadcast': 200pps, 'multicast': 200pps}, qos_schedule_profile: dwrr, aclv4_in: testv4, aclv6_in: testv6, aclmac_in: testmac, state: 'present' }
