---
-  hosts: topflite

   tasks:
     - name: Layer3 Interface configuration
       arubaoscx_l3_interface:
         interface: "{{ item.interface }}"
         admin_state: "{{ item.admin_state }}"
         description: "{{ item.description }}"
         ipv4: "{{ item.ipv4 }}"
         ipv6: "{{ item.ipv6 }}"
         qos_rate: "{{ item.qos_rate }}"
         qos_schedule_profile: "{{ item.qos_schedule_profile }}"
         aclv4_in: "{{ item.aclv4_in }}"
         aclv6_in: "{{ item.aclv6_in }}"
         aclmac_in: "{{ item.aclmac_in }}"
         aclv4_out: "{{ item.aclv4_out }}"
         vrf: "{{ item.vrf }}"
         state: "{{ item.state }}"
       with_items:
         - { interface: 1/1/4, admin_state: up, description: test, ipv4: ['10.10.10.2/24', '1.2.3.4/24'], ipv6: ['2001:db8::1234/32', '2000:db8::1234/32'], qos_rate: {'unknown-unicast': 100pps, 'broadcast': 200pps, 'multicast': 200pps}, qos_schedule_profile: dwrr, aclv4_in: testv4, aclv6_in: testv6, aclmac_in: testmac, aclv4_out: testv4egress, vrf: myvrf, state: present }

