---
-  hosts: topflite

   tasks:
     - name: VLAN configuration
       arubaoscx_vlan:
         vlan_id: "{{ item.vlan_id }}"
         name: "{{ item.name }}"
         description: "{{ item.description }}"
         interfaces: "{{ item.interfaces }}"
         state: "{{ item.state }}"
       with_items:
         - { vlan_id: 2, name: VLAN2, description: testvlan, interfaces: ['1/1/2', '1/1/4'], state: 'present' }
