---
-  hosts: topflite

   tasks:
     - name: VLAN Interface configuration
       arubaoscx_vlan_interface:
         interface: "{{ item.interface }}"
         admin_state: "{{ item.admin_state }}"
         description: "{{ item.description }}"
         ipv4: "{{ item.ipv4 }}"
         ipv6: "{{ item.ipv6 }}"
         ip_helper_address: "{{ item.ip_helper_address }}"
         active_gateway_ip: "{{ item.active_gateway_ip }}"
         active_gateway_mac_v4: "{{ item.active_gateway_mac_v4 }}"
         vrf: "{{ item.vrf }}"
         state: "{{ item.state }}"
       with_items:
         - { interface: vlan2, admin_state: up, description: test, ipv4: ['10.10.10.2/24', '1.2.3.4/24'], ipv6: ['2001:db8::1234/32', '2000:db8::1234/32'], ip_helper_address: ['10.6.7.10'], active_gateway_ip: '172.1.3.254', active_gateway_mac_v4: '98:F2:68:FF:B3:00', vrf: default, state: present }

