---
- hosts: localhost
  connection: local
  tasks:
    - name: Store Global variables in localhost
      block:
        - set_fact:
            site_data: "{{ hostvars[groups[site][0]] }}"
        - set_fact:
            cx_group_name: "{{ site_data.cx_group_name }}"  # Group for the CX

- hosts: "{{ hostvars.localhost.cx_group_name }}"
  connection: local
  gather_facts: no
  tasks:
    - name: Confgiure Switch
      block:
        #  Login to ArubaOS CX switches
        - name: Login CX
          include: aruba_task_lists/aos_cx/login_cx.yml

        # !Enter AOS-CX tasks here!

      always:
        # Logout from ArubaOS Switch
        - name: Logout CX
          include: aruba_task_lists/aos_cx/logout_cx.yml

