---
- hosts: branch*_cxs
  connection: local
  gather_facts: no
  tasks:
    - name: Confgiure Switch
      block:
        #  Login to ArubaOS CX switches
        - name: Login CX
          include: aruba_task_lists/aos_cx/login_cx.yml

        # !Enter AOS-CX tasks here!

      always:
        # Logout from ArubaOS Switch
        - name: Logout CX
          include: aruba_task_lists/aos_cx/logout_cx.yml

