---
- hosts: branch*_switches
  connection: local
  gather_facts: no
  tasks:
    - name: Confgiure Switch
      block:
        # Login to ArubaOS switches
        - name: Login
          include: aruba_task_lists/aos_switch/login_switch.yml

        # !Enter AOS-Switch tasks here!

      always:
        # Logout from ArubaOS Switch
        - name: Logout
          include: aruba_task_lists/aos_switch/logout_switch.yml

