---
# AOS-Switch
- hosts: branch*_switches
  connection: local
  gather_facts: no
  tasks:
    - name: Confgiure Switch
      block:
        # Login to ArubaOS switches
        - name: Login
          include: aruba_task_lists/aos_switch/login_switch.yml

        # !Enter AOS-Switch tasks here!

      always:
        # Logout from ArubaOS Switch
        - name: Logout
          include: aruba_task_lists/aos_switch/logout_switch.yml


# AOS-CX
- hosts: branch*_cxs
  connection: local
  gather_facts: no
  tasks:
    - name: Confgiure Switch
      block:
        #  Login to ArubaOS CX switches
        - name: Login CX
          include: aruba_task_lists/aos_cx/login_cx.yml

        # !Enter AOS-CX tasks here!

      always:
        # Logout from ArubaOS Switch
        - name: Logout CX
          include: aruba_task_lists/aos_cx/logout_cx.yml

