# Build Lag
- name: Get Current Lag Object
  uri:
    url: 'https://{{ ip }}/rest/v1/system/ports/{{ lag }}'
    method: GET
    body_format: json
    headers:
      cookie: "{{ cx_session.set_cookie }}"
    validate_certs: no
    status_code: 404,200
  register: get_lag_response

- fail:
    msg: "{{ lag }} already exists"
  when: get_lag_response.status == 200

- name: Create lag
  uri:
    url: 'https://{{ ip }}/rest/v1/system/ports/'
    method: POST
    body_format: json
    headers:
      cookie: "{{ cx_session.set_cookie }}"
    body: {"admin": "up", "arp_timeout": 1800, "lacp": "active", "name": "lag94", "other_config": { "mclag_enabled": true},
           "vlan_mode": "native-untagged", "vlan_tag": "/rest/v1/system/bridge/vlans/200", "vlan_trunks": ["/rest/v1/system/bridge/vlans/280","/rest/v1/system/bridge/vlans/120"], "referenced_by": "/rest/v1/system/bridge"}
    validate_certs: no
    status_code: 201
  register: put_lag_response

- name: Add to Bridge Table - 1/2
  uri:
    url: 'https://{{ ip }}/rest/v1/system/bridge?selector=configuration'
    method: GET
    body_format: json
    headers:
      cookie: "{{ cx_session.set_cookie }}"
    validate_certs: no
    status_code: 200
  register: get_bridge_response

# Set PUT Body for Bridge
- set_fact:
    bridge_put: "{{ get_bridge_response.json | add_brigde_body( lag  ) }}"

- name: Add to Bridge Table - 2/2
  uri:
    url: 'https://{{ ip }}/rest/v1/system/bridge'
    method: PUT
    body_format: json
    headers:
      cookie: "{{ cx_session.set_cookie }}"
    body: "{{ bridge_put }}"
    validate_certs: no
    status_code: 200
  register: get_vrf_response


