- hosts: switch1
  gather_facts: False

  tasks:
    - block:

      - name: add extended acl
        arubaoss_acl_policy:
          acl_name: test1
          icmp_code: 1
          icmp_type: 1
          source_ip_address: 0.0.0.0
          source_ip_mask: 255.255.255.255
          destination_ip_address: 0.0.0.0
          destination_ip_mask: 255.255.255.255
          protocol_type: "PT_ICMP"
          acl_action: AA_PERMIT

      - name: add extended acl
        arubaoss_acl_policy:
          acl_name: test
          icmp_code: 1
          icmp_type: 1
          source_ip_address: 0.0.0.0
          source_ip_mask: 255.255.255.255
          destination_ip_address: 0.0.0.0
          destination_ip_mask: 255.255.255.255
          protocol_type: "PT_ICMP"
          acl_action: AA_PERMIT
          acl_type: AT_EXTENDED_IPV4

      - name: add acl on port
        arubaoss_interface:
          interface: 5
          acl_id: "test"
          acl_direction: AD_INBOUND

      - name: add acl on port
        arubaoss_interface:
          interface: 5
          acl_id: "test1"
          acl_direction: AD_INBOUND

      - name: update acl on port
        arubaoss_interface:
          interface: 5
          acl_id: "test"
          acl_direction: AD_OUTBOUND 
          acl_type: AT_EXTENDED_IPV4 

      - name: update acl on port
        arubaoss_interface:
          interface: 5
          acl_id: "test1"
          acl_direction: AD_OUTBOUND 
          acl_type: AT_EXTENDED_IPV4 

      - name:  delete acl on port
        arubaoss_interface:
          interface: 5
          acl_id: "{{item.acl}}"
          acl_direction: "{{item.dir}}" 
          acl_type: "{{item.type}}"
          state: delete
        with_items:
          - {"acl":"test1","dir":"AD_INBOUND","type":"AT_STANDARD_IPV4"}
          - {"acl":"test1","dir":"AD_OUTBOUND","type":"AT_STANDARD_IPV4"}
          - {"acl":"test","dir":"AD_OUTBOUND","type":"AT_EXTENDED_IPV4"}
          - {"acl":"test","dir":"AD_OUTBOUND","type":"AT_EXTENDED_IPV4"}

      - name: creat vlan
        arubaoss_vlan:
          vlan_id: 50
          name: test_vlan

      - name: add acl on vlan
        arubaoss_vlan:
          vlan_id: 50
          acl_id: "test"
          acl_direction: AD_OUTBOUND 
          acl_type: AT_EXTENDED_IPV4 
          command: config_vlan_acl

      - name: update acl on vlan
        arubaoss_vlan:
          vlan_id: 50
          acl_id: "test"
          acl_direction: AD_OUTBOUND 
          acl_type: AT_EXTENDED_IPV4 
          command: config_vlan_acl
                  
      - name: delete acl on vlan
        arubaoss_vlan:
          vlan_id: 50
          acl_id: "test"
          acl_direction: AD_OUTBOUND 
          acl_type: AT_EXTENDED_IPV4 
          command: config_vlan_acl
          config: delete
        with_items:
           - 1
           - 2

      - name: enable port
        arubaoss_interface:
          interface: 5
          admin_stat: True

      - name: enable port
        arubaoss_interface:
          interface: 5
          admin_stat: True

      - name: disable port
        arubaoss_interface:
          interface: 5
          admin_stat: False

      - name: add standard acl
        arubaoss_acl_policy:
          acl_name: "{{item.acl}}"
          source_ip_address: "{{item.ip}}"
          acl_action: "{{item.action}}"
          is_log: "{{item.log}}"
          remark: testing
        with_items:
          - {"acl":"test2","action":"AA_PERMIT","ip":"any","log":False}
          - {"acl":"test3","action":"AA_PERMIT","ip":"any","log":True}

      - name: add standard acl
        arubaoss_acl_policy:
          acl_name: "{{item.acl}}"
          source_ip_address: "{{item.ip}}"
          acl_action: "{{item.action}}"
          is_log: "{{item.log}}"
          sequence_no: 10
        with_items:
          - {"acl":"test2","action":"AA_PERMIT","ip":"any","log":True}
          - {"acl":"test3","action":"AA_PERMIT","ip":"any","log":False}

      - name: add standard acl
        arubaoss_acl_policy:
          acl_name: "{{item}}"
          state: delete
        with_items:
          - test2
          - test3

