- hosts: switch1
  gather_facts: False

  tasks:
    - block:
      - name: configure interface description
        arubaoss_interface:
          interface: 5
          description: "test_interface"

      - name: configure a vlan
        arubaoss_vlan:
          vlan_id: 300
          name: "vlan300"
          config: create
          command: config_vlan

      - name: change loop-protect mode to vlan
        arubaoss_loop_protect:
          command: update
          mode: LPM_VLAN

      - name: enable loop-prtoect on vlan
        arubaoss_loop_protect:
          command: update_vlan
          vlan: 300
 
      - name: update vlan with ports
        arubaoss_vlan:
          vlan_id: 300
          name: "vlan300"
          config: create
          command: config_vlan_port
          port_id: "2"
          port_mode: "POM_TAGGED_STATIC"
 
      - name: update vlan with ip address
        arubaoss_vlan:
          vlan_id: 300
          name: "vlan300"
          config: create
          command: config_vlan_ipaddress
          vlan_ip_address: "10.10.30.40"
          version: "IAV_IP_V4"
          vlan_ip_mask: "255.255.255.0"

      - name: update vlan with dhcp helper address
        arubaoss_vlan:
          vlan_id: 300
          name: "vlan300"
          config: create
          command: config_vlan_dhcpHelperAddress
          helper_addresses: "10.10.10.100"
          version: "IAV_IP_V4"

      - name: create traffic class
        arubaoss_traffic_class:
          class_name: my_class

      - name: add match criteria
        arubaoss_traffic_class:
          class_name: my_class
          icmp_code: 1
          icmp_type: 1
          source_ip_address: 0.0.0.0
          source_ip_mask: 255.255.255.255
          destination_ip_address: 0.0.0.0
          destination_ip_mask: 255.255.255.255
          protocol_type: "PT_ICMP"
          entry_type: QTCET_MATCH
        register: class_1

      - name: add match criteria tcp
        arubaoss_traffic_class:
          class_name: my_class
          source_ip_address: 0.0.0.0
          source_ip_mask: 255.255.255.255
          destination_ip_address: 0.0.0.0
          destination_ip_mask: 255.255.255.255
          protocol_type: "PT_TCP"
          entry_type: QTCET_MATCH
        register: class_2

      - name: create qos policy
        arubaoss_qos_policy:
          policy_name: my_qos

      - name: re-create qos policy
        arubaoss_qos_policy:
          policy_name: my_qos

      - name: attach class to qos
        arubaoss_qos_policy:
          policy_name: my_qos
          class_name: my_class
          action: QPAT_RATE_LIMIT
          action_value: 1000
          sequence_no: "{{class_1.sequence_no}}"

      - name: re-attach class to qos
        arubaoss_qos_policy:
          policy_name: my_qos
          class_name: my_class
          action: QPAT_RATE_LIMIT
          action_value: 1000
          sequence_no: "{{class_1.sequence_no}}"

      - name: configure qos on port
        arubaoss_interface:
          interface: 5
          qos_policy: "my_qos"


      - name: configure qos on vlan 
        arubaoss_vlan:
          vlan_id: 300
          command: config_vlan_qos
          qos_policy: "my_qos"


      - name: add standard acl
        arubaoss_acl_policy:
          acl_name: test
          icmp_code: 1
          icmp_type: 1
          source_ip_address: 0.0.0.0
          source_ip_mask: 255.255.255.255
          destination_ip_address: 0.0.0.0
          destination_ip_mask: 255.255.255.255
          protocol_type: "PT_ICMP"
          acl_action: AA_PERMIT

      - name: add acl on port
        arubaoss_interface:
          interface: 5
          acl_id: "test"
          acl_direction: AD_INBOUND

      - name: add acl on vlan
        arubaoss_vlan:
          vlan_id: 300
          acl_id: "test"
          acl_direction: AD_OUTBOUND 
          acl_type: AT_EXTENDED_IPV4 
          command: config_vlan_acl

      - name: disable port
        arubaoss_interface:
          interface: 5
          admin_stat: False

      ignore_errors: yes

