- hosts: switch1
  gather_facts: False
  tasks:
    - block:

      - name: create ip auth all
        arubaoss_ip_auth:
          auth_ip: 10.0.12.91
          mask: 255.255.248.0
          access_role: AR_MANAGER
          access_method: AM_ALL
        register: auth_1

      - name: create ip auth 
        arubaoss_ip_auth:
          auth_ip: 10.0.12.92
          mask: 255.255.248.0
          access_role: AR_MANAGER
          access_method: AM_WEB
        register: auth_2

      - name: re-create ip auth all
        arubaoss_ip_auth:
          auth_ip: 10.0.12.91
          mask: 255.255.248.0
          access_role: AR_MANAGER
          access_method: AM_ALL

      - name: delete ip auth all
        arubaoss_ip_auth:
          auth_ip: 10.0.12.92
          auth_id: "{{auth_1.id}}"
          state: delete

      - name: create ip auth operator all
        arubaoss_ip_auth:
          auth_ip: 10.0.12.39
          mask: 255.255.248.0
          access_role: AR_OPERATOR
          access_method: AM_ALL
        register: auth_3

      - name: create ip auth operator web 
        arubaoss_ip_auth:
          auth_ip: 10.0.12.39
          mask: 255.255.248.0
          access_role: AR_OPERATOR
          access_method: AM_WEB
        register: auth_4

      - name: re-create ip auth operator web 
        arubaoss_ip_auth:
          auth_ip: 10.0.12.39
          mask: 255.255.248.0
          access_role: AR_OPERATOR
          access_method: AM_WEB

      - name: delete ip auth all
        arubaoss_ip_auth:
          auth_id: "{{item}}"
          state: delete
        with_items:
          - "{{auth_2.id}}"
          - "{{auth_3.id}}"
          - "{{auth_4.id}}"


      ignore_errors: yes


