- hosts: switch1
  gather_facts: False
  tasks: 
   - block:

     - name: disable routing
       arubaoss_routing:
         state: delete

     - name: add route vlan
       arubaoss_ip_route:
         ip_route_mode: IRM_VLAN 
         ip_version: IAV_IP_V4
         destination: 1.1.1.0
         mask: 255.255.255.0
         destination_vlan: 20
         name: "test"

     - name: add route vlan
       arubaoss_ip_route:
         ip_route_mode: IRM_VLAN 
         ip_version: IAV_IP_V4
         destination: 1.1.1.0
         mask: 255.255.255.0
         destination_vlan: 20
         name: "test"


     - name: add route blackhole
       arubaoss_ip_route:
         ip_route_mode: IRM_BLACK_HOLE
         ip_version: IAV_IP_V4
         destination: 2.2.2.0
         mask: 255.255.255.0

     - name: delete route vlan
       arubaoss_ip_route:
         ip_route_mode: IRM_VLAN
         destination_vlan: 20
         destination: 1.1.1.0
         mask: 255.255.255.0
         state: delete

     - name: delete route blackhole
       arubaoss_ip_route:
         ip_route_mode: IRM_BLACK_HOLE
         destination: 2.2.2.0
         mask: 255.255.255.0
         state: delete

     - name: delete route blackhole
       arubaoss_ip_route:
         ip_route_mode: IRM_BLACK_HOLE
         destination: 2.2.2.0
         mask: 255.255.255.0
         state: delete


     ignore_errors: yes 

