- hosts: switch1
  gather_facts: False
  tasks:
    - block:
      - name: configure syslog server 
        arubaoss_syslog:
          server_address: 1.1.1.1
          protocol: TP_TCP

      - name: configure syslog server 
        arubaoss_syslog:
          server_address: 1.1.1.1
          protocol: TP_TCP

      - name: delete syslog server
        arubaoss_syslog:
          server_address: 1.1.1.1
          state: delete

      - name: re-configure syslog server 
        arubaoss_syslog:
          server_address: 1.1.1.1
          protocol: TP_TCP

      - name: update syslog server 
        arubaoss_syslog:
          server_address: 1.1.1.1
          protocol: TP_UDP
          description: test

      - name: delete syslog server 
        arubaoss_syslog:
          server_address: 1.1.1.1
          state: delete

      - name: delete syslog server 
        arubaoss_syslog:
          server_address: 1.1.1.1
          state: delete

